name: Test and Deploy bioimageio.torch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  conda-build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
    - name: linux conda build
      shell: bash -l {0}
      run: |
        conda install -n base -c conda-forge conda-build pip -y
        conda build -c pytorch -c ilastik-forge -c conda-forge conda-recipe
